import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ocrAFont } from "./font";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ocrAFont} ${ocrAFont} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
